# -*- coding: utf-8 -*-
"""codigo_trafico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lA9t5urrwKJojDzYwqW48vlRiWx6dEoh
"""

#%%
import pandas as pd

# Verificamos formatos con uno de los csv de enero de 2022
df_test = pd.read_csv(
    r"C:\Users\danie\Documents\Ciencia de Datos\Curso 25-26\Actividades S2\Open Data II\Trafico\Trafico2022\2022_01_Gener_TRAMS_TRAMS.csv",
    nrows=5
)

print(df_test.columns.tolist())
print(df_test.head())
print(df_test.dtypes)
#%% md
'''Leemos en chunks porque los datos son inmensos
Parseamos a timestamp
Juntamos por fecha y turno'''
#%%
# Función para asignar turno

def timestamp_to_torn(hora):
    if 6<=hora<14:
        return 'Matí'
    elif 14<=hora<22:
        return 'Tarda'
    else:
        return 'Nit'

#%%
# Usamos chunks para leer los archivos y procesarlos

chunks_agregados= []

for chunk in pd.read_csv(
    r"C:\Users\danie\Documents\Ciencia de Datos\Curso 25-26\Actividades S2\Open Data II\Trafico\Trafico2022\2022_01_Gener_TRAMS_TRAMS.csv",
    chunksize=200_000,
    dtype={"data": str}
):
    chunk["datetime"]        = pd.to_datetime(chunk["data"], format="%Y%m%d%H%M%S", errors="coerce")
    chunk["fecha"]           = chunk["datetime"].dt.date
    chunk["Descripcio_torn"] = chunk["datetime"].dt.hour.apply(timestamp_to_torn)

    agg = (
        chunk.groupby(["fecha", "Descripcio_torn"])["estatActual"]
        .agg(lambda x: (x >= 2).mean())  # % trams congestionados
        .reset_index()
        .rename(columns={"estatActual": "pct_congestion"})
    )
    chunks_agregados.append(agg)  # ← esta línea también tiene que estar dentro

# Esto ya va fuera del for
df_enero= (
    pd.concat(chunks_agregados)
    .groupby(["fecha", "Descripcio_torn"])["pct_congestion"]
    .mean()
    .reset_index()
)
df_enero["fecha"]= pd.to_datetime(df_enero["fecha"])

print(df_enero.head())
print(f"\nFilas: {len(df_enero)}")
#%%
# Aplicamos en todos los meses

from pathlib import Path

BASE_DIR = Path(r"C:\Users\danie\Documents\Ciencia de Datos\Curso 25-26\Actividades S2\Open Data II\Trafico")

MESES_CAT = {
    1: "Gener", 2: "Febrer", 3: "Marc", 4: "Abril",
    5: "Maig", 6: "Juny", 7: "Juliol", 8: "Agost",
    9: "Setembre", 10: "Octubre", 11: "Novembre", 12: "Desembre"
}

def procesar_csv_trafico(filepath):
    chunks_agregados= []
    for chunk in pd.read_csv(filepath, chunksize=200_000, dtype={"data": str}):
        chunk["datetime"]        = pd.to_datetime(chunk["data"], format="%Y%m%d%H%M%S", errors="coerce")
        chunk["fecha"]           = chunk["datetime"].dt.date
        chunk["Descripcio_torn"] = chunk["datetime"].dt.hour.apply(timestamp_to_torn)
        agg= (
            chunk.groupby(["fecha", "Descripcio_torn"])["estatActual"]
            .agg(lambda x: (x >= 2).mean())
            .reset_index()
            .rename(columns={"estatActual": "pct_congestion"})
        )
        chunks_agregados.append(agg)

    df= (
        pd.concat(chunks_agregados)
        .groupby(["fecha", "Descripcio_torn"])["pct_congestion"]
        .mean()
        .reset_index()
    )
    df["fecha"]= pd.to_datetime(df["fecha"])
    return df


# Iterar todos los años y meses
todos= []

for año in [2022, 2023, 2024, 2025]:
    carpeta= BASE_DIR / f"Trafico{año}"
    for mes, nombre_mes in MESES_CAT.items():
        if año == 2023 and mes == 10:
            print(f"  {año}-{mes:02d}: se simulará después")
            continue
        patron = list(carpeta.glob(f"{año}_{mes:02d}_{nombre_mes}*"))
        if not patron:
            print(f"  ⚠ No encontrado: {año}-{mes:02d}")
            continue
        print(f"  Procesando {año}-{mes:02d}...", end=" ")
        df_mes = procesar_csv_trafico(patron[0])
        todos.append(df_mes)
        print(f"{len(df_mes)} filas")

df_trafico = pd.concat(todos, ignore_index=True).sort_values("fecha").reset_index(drop=True)
print(f"\nTotal filas: {len(df_trafico)}")
print(f"Rango: {df_trafico['fecha'].min()} → {df_trafico['fecha'].max()}")
#%%
print(df_trafico.shape)
print(df_trafico["fecha"].min(), "→", df_trafico["fecha"].max())
print(df_trafico.isnull().sum())

# Ver qué meses tenemos
df_trafico["año_mes"]= df_trafico["fecha"].dt.to_period("M")
print(df_trafico["año_mes"].unique())
#%%
# Simulamos octubre 2023

import numpy as np

# Octubres de referencia (2022 y 2024)
oct_ref= df_trafico[df_trafico["fecha"].dt.month == 10].copy()
oct_ref["dia_mes"]= oct_ref["fecha"].dt.day

media_oct= (
    oct_ref.groupby(["dia_mes", "Descripcio_torn"])["pct_congestion"]
    .mean()
    .reset_index()
)

# Generar fechas octubre 2023
fechas_oct23= pd.date_range("2023-10-01", "2023-10-31")
turnos= ["Matí", "Tarda", "Nit"]

oct23= pd.DataFrame([
    {"fecha": f, "Descripcio_torn": t, "dia_mes": f.day}
    for f in fechas_oct23
    for t in turnos
])

oct23= oct23.merge(media_oct, on=["dia_mes", "Descripcio_torn"], how="left")

# Ruido ±5%
np.random.seed(42)
oct23["pct_congestion"]= oct23["pct_congestion"] * np.random.uniform(0.95, 1.05, len(oct23))
oct23= oct23[["fecha", "Descripcio_torn", "pct_congestion"]]

# Añadir al dataframe principal
df_trafico= (
    pd.concat([df_trafico, oct23], ignore_index=True)
    .sort_values("fecha")
    .reset_index(drop=True)
)

print(f"Total filas: {len(df_trafico)}")
print(f"Meses únicos: {df_trafico['fecha'].dt.to_period('M').nunique()}")
#%%
# Guardamos el csv final
df_trafico.to_csv(
    r"C:\Users\danie\Documents\Ciencia de Datos\Curso 25-26\Actividades S2\Open Data II\Trafico\trafico_agregado.csv",
    index=False
)
print("Guardado")
#%%
df_trams= pd.read_csv(r"C:\Users\danie\Documents\Ciencia de Datos\Curso 25-26\Actividades S2\Open Data II\Trafico\transit_relacio_trams_format_long.csv")
print(df_trams.shape)
print(df_trams.columns.tolist())
print(df_trams.head(5))
#%%
# Centroide por Tram
df_tram_coords= (
    df_trams.groupby("Tram")
    .agg(lon=("Longitud", "mean"), lat=("Latitud", "mean"))
    .reset_index()
)

print(df_tram_coords.shape)
print(df_tram_coords.head(5))
#%%
# Coordenadas centrales de los 10 distritos de Barcelona
distritos= pd.DataFrame({
    "Codi_districte": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Nom_districte": [
        "Ciutat Vella", "Eixample", "Sants-Montjuïc", "Les Corts",
        "Sarrià-Sant Gervasi", "Gràcia", "Horta-Guinardó",
        "Nou Barris", "Sant Andreu", "Sant Martí"
    ],
    "lat_dist": [41.3804, 41.3927, 41.3676, 41.3883,
                 41.4073, 41.4023, 41.4197,
                 41.4408, 41.4300, 41.4155],
    "lon_dist": [2.1727, 2.1540, 2.1489, 2.1317,
                 2.1350, 2.1579, 2.1699,
                 2.1800, 2.1844, 2.2012]
})

# Asignar cada tram al distrito más cercano (distancia euclídea)
def distrito_mas_cercano(row):
    dists= np.sqrt(
        (distritos["lat_dist"] - row["lat"]) ** 2 +
        (distritos["lon_dist"] - row["lon"]) ** 2
    )
    idx = dists.idxmin()
    return distritos.loc[idx, "Codi_districte"]

df_tram_coords["Codi_districte"]= df_tram_coords.apply(distrito_mas_cercano, axis=1)

print(df_tram_coords.head(10))
print("\nTrams por distrito:")
print(df_tram_coords["Codi_districte"].value_counts().sort_index())
#%%
def procesar_csv_trafico_distrito(filepath, df_tram_coords):
    chunks_agregados= []
    for chunk in pd.read_csv(filepath, chunksize=200_000, dtype={"data": str}):
        # Unir con distrito
        chunk= chunk.merge(df_tram_coords[["Tram", "Codi_districte"]],
                           left_on="idTram", right_on="Tram", how="left")
        chunk= chunk.dropna(subset=["Codi_districte"])
        chunk["Codi_districte"]= chunk["Codi_districte"].astype(int)

        # Parsear timestamp
        chunk["datetime"]        = pd.to_datetime(chunk["data"], format="%Y%m%d%H%M%S", errors="coerce")
        chunk["fecha"]           = chunk["datetime"].dt.date
        chunk["Descripcio_torn"] = chunk["datetime"].dt.hour.apply(timestamp_to_torn)

        # Agregar por distrito + fecha + turno
        agg= (
            chunk.groupby(["Codi_districte", "fecha", "Descripcio_torn"])["estatActual"]
            .agg(lambda x: (x >= 2).mean())
            .reset_index()
            .rename(columns={"estatActual": "pct_congestion"})
        )
        chunks_agregados.append(agg)

    df= (
        pd.concat(chunks_agregados)
        .groupby(["Codi_districte", "fecha", "Descripcio_torn"])["pct_congestion"]
        .mean()
        .reset_index()
    )
    df["fecha"]= pd.to_datetime(df["fecha"])
    return df
#%%
df_test= procesar_csv_trafico_distrito(
    BASE_DIR / "Trafico2022" / "2022_01_Gener_TRAMS_TRAMS.csv",
    df_tram_coords
)
print(df_test.shape)
print(df_test.head(9))
#%%
todos_distrito= []

for año in [2022, 2023, 2024, 2025]:
    carpeta= BASE_DIR / f"Trafico{año}"
    for mes, nombre_mes in MESES_CAT.items():
        if año == 2023 and mes == 10:
            print(f"  {año}-{mes:02d}: se simulará después")
            continue
        patron= list(carpeta.glob(f"{año}_{mes:02d}_{nombre_mes}*"))
        if not patron:
            print(f"  ⚠ No encontrado: {año}-{mes:02d}")
            continue
        print(f"  Procesando {año}-{mes:02d}...", end=" ")
        df_mes= procesar_csv_trafico_distrito(patron[0], df_tram_coords)
        todos_distrito.append(df_mes)
        print(f"{len(df_mes)} filas")

df_trafico_dist= pd.concat(todos_distrito, ignore_index=True).sort_values(["fecha", "Codi_districte"]).reset_index(drop=True)
print(f"\nTotal filas: {len(df_trafico_dist)}")
print(f"Rango: {df_trafico_dist['fecha'].min()} → {df_trafico_dist['fecha'].max()}")
#%% md
# simulamos octubre 2023 por distrito
#%%
# Octubres de referencia por distrito
oct_ref= df_trafico_dist[df_trafico_dist["fecha"].dt.month == 10].copy()
oct_ref["dia_mes"]= oct_ref["fecha"].dt.day

media_oct= (
    oct_ref.groupby(["Codi_districte", "dia_mes", "Descripcio_torn"])["pct_congestion"]
    .mean()
    .reset_index()
)

# Generar fechas octubre 2023 × 10 distritos × 3 turnos
fechas_oct23= pd.date_range("2023-10-01", "2023-10-31")
turnos= ["Matí", "Tarda", "Nit"]
distritos_cod= list(range(1, 11))

oct23= pd.DataFrame([
    {"fecha": f, "Codi_districte": d, "Descripcio_torn": t, "dia_mes": f.day}
    for f in fechas_oct23
    for d in distritos_cod
    for t in turnos
])

oct23= oct23.merge(media_oct, on=["Codi_districte", "dia_mes", "Descripcio_torn"], how="left")

np.random.seed(42)
oct23["pct_congestion"]= oct23["pct_congestion"] * np.random.uniform(0.95, 1.05, len(oct23))
oct23= oct23[["Codi_districte", "fecha", "Descripcio_torn", "pct_congestion"]]

df_trafico_dist= (
    pd.concat([df_trafico_dist, oct23], ignore_index=True)
    .sort_values(["fecha", "Codi_districte"])
    .reset_index(drop=True)
)

df_trafico_dist["fecha"]= pd.to_datetime(df_trafico_dist["fecha"])

print(f"Total filas: {len(df_trafico_dist)}")
print(f"Meses únicos: {df_trafico_dist['fecha'].dt.to_period('M').nunique()}")

#%%
df_trafico_dist.to_csv(
    r"C:\Users\danie\Documents\Ciencia de Datos\Curso 25-26\Actividades S2\Open Data II\Trafico\trafico_agregado_distrito.csv",
    index=False
)
print("Guardado")