name: 'proyecto_accidentes'
version: '1.0.0'
config-version: 2

profile: 'proyecto_accidentes'

# modelos
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración de materialización por defecto
models:
  proyecto_accidentes:
    staging:
      +schema: silver
      +materialized: view
    mart:
      +schema: gold
      +materialized: table