# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zA9b-6Euf5xXVNz1otWDTMZqbRm64gy1
"""

#%% md
#IMPORTACIÓN DE LIBRERÍAS Y DE DF
#%%
import io
import numpy as np
import pandas as pd
import requests
#%%
df= pd.read_excel("datos_limpios.xlsx")
#%%
df.head()
#%% md
#EXTRACCIÓN DE DATOS METEREOLÓGICOS
#%%
#Latitud Barcelona
latitude=41.3874
longitude=2.1686

# Fechas
start_date= "2022-01-01"
end_date= "2025-12-31"

url= "https://archive-api.open-meteo.com/v1/archive"

params= {
    "latitude": latitude,
    "longitude": longitude,
    "start_date": start_date,
    "end_date": end_date,
    "hourly": [
        "temperature_2m", #en celsius
        "precipitation", #suma de lluvia, llovizna y nieve. Valor en mm de agua
        "rain",
        "wind_speed_10m", #velocidad del viento a 10 metros de altura, en km/h
        "weather_code" #código numérico que representa las condiciones meteorológicas (por ejemplo, soleado, nublado, lluvioso, etc.)
    ],
    "timezone": "Europe/Madrid"
}

response= requests.get(url, params=params)
data=response.json()

meteo= pd.DataFrame(data["hourly"])
meteo["time"] = pd.to_datetime(meteo["time"])

#%%
# Visualizamos como es meteo
meteo.head()
#%%
meteo.isna().sum()
#%%
meteo["Data"]=meteo["time"].dt.date
meteo["Hora_dia"]=meteo["time"].dt.hour
meteo.head()
#%%
def asignar_turno(hora):
    if 6 <= hora < 14:
        return "Matí"
    elif 14 <= hora < 22:
        return "Tarda"
    else:
        return "Nit"

meteo["Descripcio_torn"]= meteo["Hora_dia"].apply(asignar_turno)

meteo.head()
#%%
meteo.shape
#%%
meteo_turno= meteo.groupby(["Data", "Descripcio_torn"]).agg({
    "temperature_2m": "mean",
    "precipitation": "sum",
    "rain": "sum",
    "wind_speed_10m": "mean",
    "weather_code": "max" #Si en un turno hubo horas despejadas y una hora con lluvia, el máximo puede ayudarnos a quedarnos con la condición más “intensa” del turno.
}).reset_index()
#%%
meteo_turno.head(10)
#%%
# Confirmamos que hay 3 turnos por día
meteo_turno["Data"].value_counts()
#%%
meteo_turno.to_csv("datos_meteorologicos_turno.csv", index=False)