# -*- coding: utf-8 -*-
"""generate_simulated_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SrT7V5ovewvUsncMqbDm2pYkUNPp-f2_
"""

# Install faker if needed
!pip install faker

import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime

# =========================
# CONFIGURACIÓN
# =========================
INPUT_FILE = "../files/data_cleaned.csv"
OUTPUT_FILE = "data_simulated.csv"

N_NEW_ROWS = 50000

fake = Faker("es_ES")

# =========================
# DICCIONARIOS CATALÁN
# =========================
dias_semana = {
    0: "Dilluns",
    1: "Dimarts",
    2: "Dimecres",
    3: "Dijous",
    4: "Divendres",
    5: "Dissabte",
    6: "Diumenge"
}

meses_cat = {
    1: "Gener",
    2: "Febrer",
    3: "Març",
    4: "Abril",
    5: "Maig",
    6: "Juny",
    7: "Juliol",
    8: "Agost",
    9: "Setembre",
    10: "Octubre",
    11: "Novembre",
    12: "Desembre"
}

# =========================
# LOAD REAL DATA
# =========================
print("Cargando dataset oficial...")

df_real = pd.read_csv(INPUT_FILE)

print(f"Filas originales: {len(df_real)}")

# =========================
# GENERATE SIMULATED DATA
# =========================
simulated_rows = []

for i in range(N_NEW_ROWS):

    # coger fila aleatoria real
    sample = df_real.sample(1).iloc[0]

    # DATOS SIMULADOS SOLO 2026
    year = 2026

    # generar fecha aleatoria
    mes = random.randint(1, 12)

    dia = random.randint(1, 28)

    hora = random.randint(0, 23)

    fecha = datetime(
        year,
        mes,
        dia,
        hora
    )

    # pequeñas variaciones coordenadas
    latitud = (
        float(sample["latitud"])
        +
        np.random.normal(0, 0.002)
    )

    longitud = (
        float(sample["longitud"])
        +
        np.random.normal(0, 0.002)
    )

    # generar turno según hora
    if 6 <= hora < 14:
        turno = "Matí"

    elif 14 <= hora < 22:
        turno = "Tarda"

    else:
        turno = "Nit"

    # =========================
    # NUEVA FILA
    # =========================
    new_row = {

        "numero_expedient":
            f"2026SIM{str(i).zfill(6)}",

        "codi_districte":
            sample["codi_districte"],

        "nom_districte":
            sample["nom_districte"],

        "codi_barri":
            sample["codi_barri"],

        "nom_barri":
            sample["nom_barri"],

        "codi_carrer":
            sample["codi_carrer"],

        "nom_carrer":
            sample["nom_carrer"],

        "num_postal":
            sample["num_postal"],

        "descripcio_dia_setmana":
            dias_semana[fecha.weekday()],

        "nk_Any":
            year,

        "mes_any":
            mes,

        "nom_mes":
            meses_cat[mes],

        "dia_mes":
            dia,

        "hora_dia":
            hora,

        "descripcio_torn":
            turno,

        "longitud":
            longitud,

        "latitud":
            latitud,

        "causa":
            sample["causa"],

        "data":
            fecha,

        "_id":
            i + 1000000,

        "etl_fecha_ingesta":
            datetime.now()
    }

    simulated_rows.append(new_row)

# =========================
# CREATE DATAFRAME
# =========================
df_simulated = pd.DataFrame(simulated_rows)

print(f"Filas simuladas: {len(df_simulated)}")

# =========================
# SAVE CSV
# =========================
df_simulated.to_csv(
    OUTPUT_FILE,
    index=False
)

print(f"Dataset guardado: {OUTPUT_FILE}")

print("✔ Generación de datos simulados completada")