name: Update Dataset

permissions:
  contents: write

on:
  schedule:
    - cron: '0 6 * * 1'   # cada Lunes a las 6
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install pandas requests

      - name: Ejecutar script
        run: python pipeline.py

      - name: Commit y push del dataset
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data_cleaned.csv
          git commit -m "Update dataset" || echo "No changes"
          git push
